# Numpy

ndarry: N차원(Dimension) 배열(Array) 객체

In [2]:
#ndarray 생성
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3], [2,3,4]])

In [3]:
print(array1) #1차원 Shape(3,)
print(array2) #2차원 Shape(2,3)

[1 2 3]
[[1 2 3]
 [2 3 4]]


ndarray의 **shape**는 `ndarray.shape` 속성으로, **차원**은 `ndarray.ndim` 속성으로 알 수 있다.

**ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다.** 즉, 한 개의 ndarray객체에 int와 float가 함께 있을 수 없다.
ndarray내의 데이터 타입은 `ndarray.dtype`으로 확인할 수 있다.


## ndarry 타입 변환
**astype()**을 이용
- 변경을 원하는 타입을 astype()에 인자로 입력
- 대용량 데이터를 ndarray로 만들 때 메모리를 절약하기 위해 자주 사용
    0,1,2와 같이 크지 않는 범위의 숫자를 위해서 64bit float형 보다는 8bit 또는 16bit의 integer형으로 변환하는 것이 훨씬 메모리를 많이 절약하게 된다.

**대용량 데이터를 다룰시에는 메모리 절약을 위해서 형변환을 고려해야한다.**


## Numpy ndarray의 axis축
axis 0 행 / axis 1 열 / axis 2 3차원 축(z축)

In [8]:
import numpy as np

list1 = [1,2,3]
print('list type', type(list1))

array1 = np.array(list1)
print('array1 type', type(array1))
print('array1 shape:', array1.shape)

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type', type(array2))
print('array2 shape:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type', type(array3))
print('array3 shape:', array3.shape)

print(f'1번:{array1.ndim}차원, 2번:{array2.ndim}차원, 3번:{array3.ndim}차원')

list type <class 'list'>
array1 type <class 'numpy.ndarray'>
array1 shape: (3,)
array2 type <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type <class 'numpy.ndarray'>
array3 shape: (1, 3)
1번:1차원, 2번:2차원, 3번:2차원


In [11]:
# 데이터 타입
print(array1.dtype)

#데이터 타입이 자동변환된다.
test_array = np.array([1, 2, 'test']) #int -> <U11
print(test_array)

test_array = np.array([1, 2, 3.0]) #int -> float
print(test_array)

int32
<U11
[1. 2. 3.]


### astype()을 통한 타입 변환

In [13]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float.dtype)

float64


### ndarray에서 axis 기반의 연산함수 수행

In [14]:
array_axios = np.array([[1,2,3], [2,3,4]])

print(array_axios.sum()) #전체 더하기
print(array_axios.sum(axis=0)) #x방향(행)
print(array_axios.sum(axis=1)) #y방향(열)

15
[3 5 7]
[6 9]


## ndarray 편리하게 생성하기
:주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야할 경우 사용
- arange()
- zeros()
- ones()

In [17]:
# arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# zeros()
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones()
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()
reshape(-1, 5): 인자에 -1을 부여하면 -1에 해당하는 axis의 크기는 가변적이되 -1이 아닌 인자값에 해당하는 axis 크기는 인자값으로 고정되어 ndarray의 shape를 변환

reshape(-1, -1)은 사용할 수 없다.

In [20]:
# reshape()
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2, 5)
print(array2)

array3 = array1.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환

In [24]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2)

array3 = array1.reshape(5, -1)
print(array3)

array2d_1 = array1.reshape(-1, 1)
print(array2d_1)
print(array2d_1.shape, array2d_1.ndim)

array1d = array1.reshape(-1)
print(array1d)
print(array1d.shape, array1d.ndim)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1) 2
[0 1 2 3 4 5 6 7 8 9]
(10,) 1
