# ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

| 인덱싱 유형 | 설 명 |
| ---- | ---- |
| 특정 위치의 단일값 추출 | 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨 |
| 슬라이싱(Slicing) | 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식. `시작 인덱스:종료인덱스` 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 ndarray를 반환 |
| 팬시 인덱싱(Fancy Indexing) | 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정해 해당 위치에 있는 ndarray를 반환 |
| **불린 인덱싱(Boolean Indexing)** | 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 ndarray를 반환 |



## 단일 인덱싱

In [1]:
import numpy as np

array1d = np.arange(start=1, stop= 27, step=3)
print(array1d)
print(array1d.shape)

# 단일 인덱싱
print(array1d[-1])
array1d[0] = 100
print(array1d)

[ 1  4  7 10 13 16 19 22 25]
(9,)
25
[100   4   7  10  13  16  19  22  25]


In [2]:
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])

[[100   4   7]
 [ 10  13  16]
 [ 19  22  25]]
100


## 슬라이싱(Slicing)

In [3]:
print(array1d[3:6])
print(array2d[0:2, 1:3])

[10 13 16]
[[ 4  7]
 [13 16]]


## 팬싱 인덱싱(fancy indexing)

In [4]:
print(array2d[[0,1], [1,2]])
print(array2d[[0,1], 1:3])
print(array2d[[0,1]])

[ 4 16]
[[ 4  7]
 [13 16]]
[[100   4   7]
 [ 10  13  16]]


## 불린 인덱싱(Boolean indexing)

In [5]:


"""
array1d에서 20보다 큰 값을 출력하세요
"""
# 일반 인덱스
target = []
for i in range(len(array1d)):
    if array1d[i] > 20:
        target.append(array1d[i])
array_result = np.array(target)
print(array_result)



print(array1d > 20) #불린 인덱싱 확인
print(type(array1d > 20)) #타입 확인

#불린 인덱싱
print(array1d[array1d > 20])

[100  22  25]
[ True False False False False False False  True  True]
<class 'numpy.ndarray'>
[100  22  25]
