# Numpy 정렬과 선형대수 연산

## 정렬

### sort()
Numpy sort() 유형
- np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

<small>np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬. 내림차순으로 정렬하기 위해서는 **[::-1]**을 적용. np.sort()[::-1]과 같이 사용하면 된다.</small>

#### 2차원 배열에서 axis 기반의 sort()

In [1]:
import numpy as np

data = np.array([[8,12],[7,1]])
print(data.shape)

#파이썬과 다르게 Numpy는 sort를 해도 원본값 유지
#But, ndarray.sort()시에는 원본값이 변환됨
print(np.sort(data, axis=0))

print(np.sort(data, axis=1))

(2, 2)
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [2]:
data = np.array([[8,1],[7,12]])
print(data.shape)

print(np.sort(data, axis=0))

print(np.sort(data, axis=1))

(2, 2)
[[ 7  1]
 [ 8 12]]
[[ 1  8]
 [ 7 12]]


### argsort()
- 원본 행렬 정렬 시 정렬된 **행렬의 원래 인덱스를 필요로 할 때** np.argsort()를 이용. np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환.

In [3]:
data = np.array([5,4,2,1,3])
print(np.argsort(data)) #정렬한 후 이전값이 가지던 인덱스 반환

[3 2 4 1 0]


예시]<br/>
key-value 형태의 데이터를 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 만들고 argsort()를 이용하여 key값을 정렬

In [4]:
person_name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_value = np.array([78, 95, 84, 98, 88])

score_arg = np.argsort(score_value)

print(person_name[score_arg])
print(score_value[score_arg])

['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


## 선형대수 연산

### 행렬 내적

#### np.dot(A, B)

In [5]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])

print(np.dot(A, B))

[[ 58  64]
 [139 154]]


### 전치 행렬
#### np.transpost(A)

In [6]:
A = [[1,2], [3,4]]

np.transpose(A)

array([[1, 3],
       [2, 4]])

- 넘파이는 파이썬 머신러닝을 구성하는 핵심 기반으로 반드시 이해 필요

- 넘파이 API는 매우 넓은 범위를 다루고 있으므로 머신러닝 애플리케이션을 작성할 때 중요하게 활용될 수 있는 핵심 개념 위주로 숙지하는 것이 좋다

- 넘파이는 판다스에 비해서 친절한 API를 제공하지 않는다. **2차원의 데이터라면 데이터 가공을 위해서 Pandas를 이용하는 것이 효율적**이다.